# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(120, 70, 101, 21))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 60, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.thread1 = QtWidgets.QPushButton(Dialog)
        self.thread1.setGeometry(QtCore.QRect(60, 110, 75, 23))
        self.thread1.setObjectName("thread1")
        self.thread2 = QtWidgets.QPushButton(Dialog)
        self.thread2.setGeometry(QtCore.QRect(60, 150, 75, 23))
        self.thread2.setObjectName("thread2")
        self.t1off = QtWidgets.QPushButton(Dialog)
        self.t1off.setGeometry(QtCore.QRect(60, 190, 75, 23))
        self.t1off.setObjectName("t1off")
        self.t2off = QtWidgets.QPushButton(Dialog)
        self.t2off.setGeometry(QtCore.QRect(60, 230, 75, 23))
        self.t2off.setObjectName("t2off")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "PORT"))
        self.thread1.setText(_translate("Dialog", "Thread1"))
        self.thread2.setText(_translate("Dialog", "Thread2"))
        self.t1off.setText(_translate("Dialog", "Thread1Off"))
        self.t2off.setText(_translate("Dialog", "Thread2Off"))
